app/formsubmit/forms.py
#! python
#
# ~/app/formsubmit/forms.py
# The forms available to the formsubmit application within the
# example flask application
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired
from wtforms.validators import Length


class AddressForm(FlaskForm):
    addr1 = StringField('Address 1', validators=[DataRequired()])
    addr2 = StringField('Address 2')
    city = StringField('City', validators=[DataRequired()])
    state = StringField(
        'State',
        validators=[
            DataRequired(),
            Length(min=2, max=2)
        ]
    )

app/__init__.py
import logging
from logging.handlers import RotatingFileHandler
import os
from flask import Flask
# from flask import request
# from flask import current_app
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import Config

db = SQLAlchemy()
migrate = Migrate()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)

    # Incorporating the Blueprints
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.formsubmit import bp as formsubmit_bp
    app.register_blueprint(formsubmit_bp)

    # ------- #
    # Logging #
    # ------- #
    # This section handles logging setup
    if not app.debug and not app.testing:
        if not os.path.exists('logs'):
            os.mkdir('logs')
        file_handler = RotatingFileHandler('logs/microblog.log',
                                           maxBytes=10240, backupCount=10)
        file_handler.setFormatter(logging.Formatter(
            '%(asctime)s %(levelname)s: %(message)s '
            '[in %(pathname)s:%(lineno)d]'))
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('Microblog startup')

    return app


# from app import models

app/formsubmit/__init__.py
from flask import Blueprint

bp = Blueprint('formsubmit', __name__)

from app.formsubmit import routes

app/formsubmit/routes.py
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from app.formsubmit import bp
from app.formsubmit.forms import AddressForm
from werkzeug.urls import url_parse


@bp.route('/formredirect', methods=['GET', 'POST'])
def formredirect():
    # formredirect demonstrates how to accept form input from a user
    # The endpoint (/formredirect) accepts GET and POST requests
    # in order to present the blank form (GET) and validate a
    # submitted form (POST)

    # First, grab the form, which must be imported at the top of the
    # file.
    form = AddressForm()

    if form.validate_on_submit():
        # Should the request be a POST, the form must be validated.
        # The validate_on_submit() method will run the form's
        # validation that was specified in the form (I.e.
        # DataRequired)

        # Handle the next page
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('main.index')
        # Handle successful submission
        return redirect(next_page)

    # Get requests, as there won't be a form submission, will pass
    # the form into the renderer along with the template to be
    # displayed by the user's browser
    return render_template(
        'formsubmit/formredirect.html',
        form=form
    )

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template
from app.main import bp


@bp.route('/')
@bp.route('/index')
def index():
    # Render index page
    return render_template('index.html')


@bp.route('/about')
def about():
    # Render about page
    return render_template('about.html')

app/thirdpartyapi/__init__.py
from flask import Blueprint

bp = Blueprint('thirdpartyapi', __name__)

from app.thirdpartyapi import routes

app/thirdpartyapi/routes.py
from flask import request
from flask import jsonify
from flask import session
from app.main import bp
import requests


# @bp.before_app_request
# def before_request():
#     if current_user.is_authenticated:
#         current_user.last_seen = datetime.utcnow()
#         db.session.commit()
#     g.locale = str(get_locale())


@bp.route('/gettoken', methods=['POST'])
def gettoken():
    # The caller should be our javascript apt which will pass in a dictionary
    if request.get_json():
        content = request.get_json()

        target = content['target']

        headers = content['headers']

        auth_req = requests.post(target, headers=headers, verify=False)

        status = auth_req.status_code

        auth_req.encoding = 'utf-8'

        return jsonify({'status': status,
                        'token_info': auth_req.text})

    else:
        return jsonify({'status': 'an error happend'})


@bp.route('/getapirequest', methods=['POST'])
def getapirequest():
    if request.get_json():
        content = request.get_json()

        target = content['target']

        headers = {
            'Authorization': 'Bearer {}'.format(session['Bearer'])
        }

        api_resp = requests.get(target, headers=headers, verify=False)

        status = api_resp.status_code

        api_resp.encoding = 'utf-8'

        return jsonify({'status': status,
                        'resp': api_resp.text})
    else:
        return jsonify({'status': 'an error happened'})


@bp.route('/addtosession', methods=['POST'])
def addtosession():
    if request.get_json():
        content = request.get_json()
        session[content['key']] = content['value']

        return jsonify({'status': 'success'})

app/templates/about.html
{# about.html #}
{# This is the about page for the Example Application #}
{% extends "base.html" %}
{% block title %}
<title>About Example</title>
{% endblock %}

{% block content %}
<h1>About Example App</h1>
<p>Python - Flask Examples is an application created to demonstrate what I've learned about Flask and building web applications.</p>
<hr>
<h2>Creator</h2>
<h3>Kyle</h3>
<hr>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8" />
    <meta name="description" content="Python - Flask Example" />
    <meta name="keywords" content="python,flask" />
    <meta name="author" content="Kyle J. Egland" />
    {% block title %}
    <title>Flask Example</title>
    {% endblock %}
    <link rel="icon" href="static/favicon/favicon.ico" />
    {% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/resetstyle.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}" />
    {% endblock %}
  </head>
  <body class="app-body" id="body">
    {# Navbar #}
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Example</a>
      {# This creates the menu button when items are collapsed #}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {# The Contents of this div is collapsable #}
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Forms
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{ url_for('formsubmit.formredirect') }}">Submit with Redirect</a>
              <a class="dropdown-item" href="#">Submit without Redirect</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
          </li>
        </ul>
        {# Search bar #}
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    {# CONTENT BLOCK #}
    {# Content from pages inheriting base.html #}
    <div class="container mx-auto mt-5" id="content">
      {% block content %}
      {% endblock %}
    </div>
    {# Script block #}
    {# Used to allow other pages to either super() and add toor exclude entirely, exchanging page specific scripts #}
    {% block script %}
    <script type="text/javascript" src="{{ url_for('static', filename='bootstrap/jquery-3.4.1.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='bootstrap/popper.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
    {% endblock %}
  </body>
</html>

app/templates/formsubmit/apitest.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Flask API Test</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon/favicon.ico') }}">
    </head>
    <body>
        <div class="container">
            <h1>API Interaction test</h1>

            <p>This is a demonstration of Flask interacting with an API</p>

            <!-- Login form -->
            <div id="apiLogin" class="card">
                <div class="card-body">
                    <h3 class="card-title">Api login info</h3>
                    <div class="form">
                        <div class="form-group">
                            <label for="apiAuthEndpoint">API Auth Endpoint</label>
                            <input class="form-control" type="text" name="apiAuthEndpoint" id="apiAuthEndpoint" aria-describedby="apiAuthEndpointHelp">
                            <small id="apiAuthEndpointHelp" class="form-text text-muted">Example: https://[MyAppServerHost]/[MyAppServerInstance]/login.svc/</small>
                        </div>
                        <div class="form-group">
                            <label for="username">API Username</label>
                            <input class="form-control" type="text" name="username" id="username">
                        </div>
                        <div class="form-group">
                            <label for="passwd">Password</label>
                            <input class="form-control" type="password" name="passwd" id="passwd">
                        </div>
                        <button id="loginButton" class="btn btn-dark">Get Token</button>
                    </div>
                </div>
            </div>

            <!-- Token Display area -->
            <div class="container">
                <span id="tokenstatus"></span><br />
                <span id="tokentype"></span><br />
                <span id="accesstoken"></span><br />
                <span id="expiresin"></span><br />
            </div>

            <!-- API Caller form -->
            <div id="apiCall" class="card">
                <div class="card-body">
                    <h3 class="card-title">Api Call</h3>
                    <div class="form">
                        <div class="form-group">
                            <label for="apiCallEndpoint">API Call Endpoint</label>
                            <input class="form-control" type="text" name="apiCallEndpoint" id="apiCallEndpoint" aria-describedby="apiCallEndpointHelp">
                            <small id="apiCallEndpointHelp" class="form-text text-muted">Example: https://[MyAppServerHost]/[MyAppServerInstance]/api/v1/endpoint/$metadata</small>
                        </div>
                        <button class="btn btn-dark" id="apiCallButton">Get Response</button>
                    </div>
                </div>
            </div>

            <!-- Data Display Area -->
            <div class="container">
                <span id="apicallresult"></span>
            </div>
        </div>
        <script src="{{ url_for('static', filename='javascript/jquery-3.2.1.js') }}"></script>
        <script src="{{ url_for('static', filename='javascript/popper.min.js') }}"></script>
        <script src="{{ url_for('static', filename='javascript/bootstrap.js') }}"></script>
        <script src="{{ url_for('static', filename='javascript/app.js') }}"></script>
    </body>
</html>

app/templates/formsubmit/formredirect.html
{# formredirect.html #}
{# This page belongs to the formsubmit app and demonstrates submitting a #}
{# form via post submit by clicking the button or hitting enter. #}
{% extends "base.html" %}
{% block title %}
<title>Welcome to Example App!</title>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm">
    <h1>Forms - Redirect submit</h1>
    <p>This page represents a (more or less) traditional form submission approach. Upon receiving the GET request from the browser for this endpoint, Flask renders the page and presents it to the user for completion. Once the user is satisfied with the form contents and submits, the browser then conducts a POST with the form's data. The POST is sent to the same endpoint which does validation before giving the form back to the user or re-directing the user to another page.</p>
    <hr>
    <form id="form-redirect" action="{{ url_for('formsubmit.formredirect') }}" method="post">
      {{ form.csrf_token }}
      {# CSRF Token is for security, we pass it to the browser and check that it is passed back when a post is made #}
      {# Address 1 Input - FORM GROUP #}
      <div class="form-group">
        {{ form.addr1.label(for="addr1Input") }}
        {{ form.addr1(class_="form-control", id="addr1Input", placeholder="(Address line 1)", value="123 4th Street", **{"aria-describedby":"addr1InputHelp"}) }}
        <small id="addr1InputHelp" class="form-text text-muted">Number and street name</small>
      </div>
      {# Address 2 Input - FORM GROUP #}
      <div class="form-group">
        {{ form.addr2.label(for="addr2Input") }}
        {{ form.addr2(class_="form-control", id="addr2Input", placeholder="(Address line 2)") }}
      </div>
      <div class="form-group">
        <label for="exampleFormControlSelect1">Example select</label>
        <select class="form-control" id="exampleFormControlSelect1">
          <option>1</option>
          <option>2</option>
          <option>3</option>
          <option>4</option>
          <option>5</option>
        </select>
      </div>
      <div class="form-group">
        <label for="exampleFormControlSelect2">Example multiple select</label>
        <select multiple class="form-control" id="exampleFormControlSelect2">
          <option>1</option>
          <option>2</option>
          <option>3</option>
          <option>4</option>
          <option>5</option>
        </select>
      </div>
      <div class="form-group">
        <label for="exampleFormControlTextarea1">Example textarea</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
      </div>
    </form>
  </div>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block title %}
<title>Welcome to Example App!</title>
{% endblock %}

{% block content %}
<h1>Welcome to my example app!</h1>
<p>This is the landing/home/index page for the Example Application (the thing you're viewing right now). First, take a look around at everything - each part of this application is intended to be interacted with. Check out each component available in the navigation bar and come back here anytime by selecting Example in the navbar. Thanks for checking out this project and enjoy!</p>
<h2>Contents</h2>
<p>This application is broken up into various "sub-applications" (referred to simplay as "app" or "apps"). Each app is meant to be an example of some way in which to accomplish something with Flask (I.e. processing a form, database CRUD operations, etc.). Each application will have some information regarding it's aims and use on the app's page. Use the navigation bar or select one of the links below</p>
{# Index navigation and descriptions #}
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <a class="nav-link active" id="v-pills-forms-tab" data-toggle="pill" href="#v-pills-forms" role="tab" aria-controls="v-pills-forms" aria-selected="true">Forms</a>
        <a class="nav-link" id="v-pills-apis-tab" data-toggle="pill" href="#v-pills-apis" role="tab" aria-controls="v-pills-apis" aria-selected="false">APIs</a>
        <a class="nav-link" id="v-pills-users-tab" data-toggle="pill" href="#v-pills-users" role="tab" aria-controls="v-pills-users" aria-selected="false">User Management</a>
      </div>
    </div>
    <!-- Force next column to break to new line -->
    <!-- <div class="w-100 d-none d-lg-block"></div> -->
    <div class="col-sm-8">
      <div class="tab-content" id="v-pills-tabContent">
        {# Forms Nav Content #}
        <div class="tab-pane fade show active" id="v-pills-forms" role="tabpanel" aria-labelledby="v-pills-forms-tab">
          <ul class="list-group">
            <li class="list-group-item"><a href="#">Form submit with redirect</a></li>
            <li class="list-group-item"><a href="#">Form submit without redirect</a></li>
          </ul>
        </div>
        {# APIs Nav Content #}
        <div class="tab-pane fade" id="v-pills-apis" role="tabpanel" aria-labelledby="v-pills-apis-tab">
          <ul class="list-group">
            <li class="list-group-item"><a href="#">Internal API</a></li>
            <li class="list-group-item"><a href="#">Third-Party API</a></li>
          </ul>
        </div>
        {# User Management Nav Content #}
        <div class="tab-pane fade" id="v-pills-users" role="tabpanel" aria-labelledby="v-pills-users-tab">
          <ul class="list-group">
            <li class="list-group-item"><a href="#">Application (Internal) Users</a></li>
            <li class="list-group-item"><a href="#">Third-Party User Auth</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}